templates/Includes/LanguageSelector.ss
Parent PR: https://github.com/silverstripe/cwp/pull/29, and issue https://github.com/silverstripe/cwp/issues/16
=> API Switch Translatable implementation for Fluent

templates/CWP/CWP/PageTypes/Layout/EventHolder.ss, templates/Includes/DateRange.ss
Also updates a couple of translation keys to be namespaced in EventHolder.ss
=> FIX Update form message handling to match core Form.ss template

package.json, readme.md
Updates links to GitLab repos for starter-theme and watea-theme. Resolves #1
=> Update references to GitLab to point to GitHub

templates/SilverStripe/Blog/Model/Layout/BlogPost.ss
=> FIX Remove reference to incorrect blog stylesheet

templates/SilverStripe/UserForms/Form/Includes/UserFormProgress.ss
=> FIX Correct unprocessed count variable in translation for step progress

templates/SilverStripe/Forms/CheckboxSetField.ss, templates/SilverStripe/Forms/OptionsetField.ss
Templates are case sensitive now.
=> FIX use correct case vars to correctly render

templates/SilverStripe/Forms/TextareaField.ss
Resolves https://github.com/silverstripe/cwp-installer/issues/16
=> FIX Encode entities appropriately using the new core method

templates/CWP/CWP/PageTypes/Layout/NewsHolder.ss, templates/Includes/EventDetail.ss, templates/Includes/EventItem.ss, templates/Includes/FilteredUpdates.ss
Resolves https://github.com/silverstripe/cwp/issues/57
=> FIX Use CLDR date formats and check for namespaced class names in conditions

templates/SilverStripe/Forms/SelectionGroup.ss
Updates to match new framework template
=> FIX Update SelectionGroup template to correctly render selected classes

templates/Includes/EventItem.ss, templates/Includes/FilteredUpdates.ss
Currently the dates on event items are in American format.
=> Change event dates to NZ format

templates/SilverStripe/UserForms/Form/Includes/UserFormStepNav.ss
Issue: https://github.com/silverstripe/silverstripe-userforms/issues/764
=> FIX Step navigation buttons are not translatable

templates/BreadcrumbsTemplate.ss
Fixes https://github.com/silverstripe/silverstripe-cms/issues/2267
=> FIX Breadcrumbs should use MenuTitle rather than Title

templates/SilverStripe/ElementalBannerBlock/Block/BannerBlock.ss, templates/SilverStripe/ElementalBlocks/Block/BannerBlock.ss
Resolves https://github.com/silverstripe/cwp-starter-theme/issues/51
=> FIX BannerBlock template now exists in the right namespace for silverstripe/elemental-bannerblock

dist/css/editor.css, dist/css/editor.min.css, dist/css/main.css, dist/css/main.min.css, dist/js/main.js, src/scss/components/nav.scss, src/scss/variables.scss
I also played around with trying to use Bootstraps "out of the box" dropdown accessibility but it has issues. Our custom accessibility code also has issues but they're not as bad as bootstraps. I'll raise an issue capturing the fact that it can be improved but I don't think it's needed for 3.0
=> FIX Resolving styling issue with dropdown toggle carets and updating colour to be more accessible

dist/css/editor.css, dist/css/editor.min.css, dist/css/main.css, dist/css/main.min.css, dist/js/main.js, src/scss/components/nav.scss, src/scss/variables.scss
Final touch up for the grey :)
=> FIX Lighten jumbotron and navigation active background colour for WCAG AA compliance

templates/CWP/CWP/PageTypes/Layout/EventHolder.ss, templates/CWP/CWP/PageTypes/Layout/EventPage.ss, templates/CWP/CWP/PageTypes/Layout/NewsHolder.ss, templates/CWP/CWP/PageTypes/Layout/NewsPage.ss, templates/SilverStripe/Blog/Model/Layout/Blog.ss, templates/SilverStripe/Blog/Model/Layout/BlogPost.ss, templates/SilverStripe/Blog/Model/Layout/Blog_profile.ss
=> Adjust sidebar positions in news, events and blog pages to align with top of content

templates/CWP/CWP/PageTypes/Layout/EventHolder.ss, templates/CWP/CWP/PageTypes/Layout/NewsHolder.ss, templates/Includes/DateRange.ss, templates/Includes/UpdateTags.ss
=> WIP FIX Remove sr-only class on filters to be available to all users

templates/SilverStripe/Blog/Includes/EntryMeta.ss
Adds some minor design changes we found suitable for [bambusa-theme](https://github.com/silverstripe-bambusa-theme) including: 
* Remove redundant whitespace when categories and/or tags don't exist
* Remove semicolons on categories, tags
=> Adds some minor design changes we found suitable for [bambusa-theme](https://github.com/silverstripe-bambusa-theme) including:

templates/Includes/DateRange.ss, templates/Includes/UpdateTags.ss
See https://github.com/silverstripe/cwp-starter-theme/pull/156 for more details cc @robbieaverill
=>  FIX Rename date range and tag keys

composer.json
https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/46#issuecomment-547734409
=> Remove branch aliases
