silverstripe/cwp-starter-theme

composer.json

SilverStripe 4.1 introduces the concept of a public subdirectory of the
installation root, which serves as the document root for the webserver. To
be compatible with this themes must now also expose their assets as they
are otherwise no longer within the webroot as they were previously. This
change needs to be made regardless of whether or not one opts into the
public webroot setup (which is currently optional).

FIX expose public resources since it's necessary

---

composer.json

Although these files are included in the dist folder that is currently
exposed, the template seems to attempt to serve them from the module root
instead - so they also need exposing.
Follows on from #20

FIX also expose ico and images from module root

---

templates/Includes/Favicon.ss
templates/Includes/Footer.ss

Resources for a theme may now live in the theme folder, in the resources
folder, or the public/resources folder; all of which are resolved at
runtime. To allow for this we can leverage the recently reintroduced
$ThemeDir variable to resolve this for us in our templates, meaning that
we get no more dead links when trying to reference theme images.

FIX Update resource references to actual locations

---

templates/Includes/PageShowcase.ss

Is obvious when using Watea theme on top of the starter theme, as it has a grey background and looks out of place.

Hide page showcase background if no features/quicklinks exist

---

templates/CWP/CWP/PageTypes/Layout/EventHolder.ss
templates/CWP/CWP/PageTypes/Layout/NewsHolder.ss

Is misleading to content authors because the content field in the CMS indicates they should be able to add content to the page

Add content field to news and events holder page templates

---

templates/SilverStripe/Registry/Layout/RegistryPage.ss

When using the starter theme with registry pages the table would not correctly display columns. This PR fixes the issue by ensuring `Columns` is called on the top level controller (like the template provided by the registry module itself exemplifies)

FIX Ensuring columns are correctly rendered for registry

---

templates/Includes/Favicon.ss

Issue: https://github.com/silverstripe/cwp-watea-theme/issues/31

FIX Starter theme now correctly resolves the favicon for the frontend

---

templates/Includes/LanguageSelector.ss

* Add dropdown-item class to dropdown menu list items
* Remove unnecessary caret span (included by default now)
* Update xs visibility classes on selected language label

FIX Language selector dropdown is now Bootstrap 4 compliant

---

templates/CWP/CWP/PageTypes/Layout/EventHolder.ss
templates/CWP/CWP/PageTypes/Layout/EventPage.ss
templates/CWP/CWP/PageTypes/Layout/NewsHolder.ss
templates/CWP/CWP/PageTypes/Layout/NewsPage.ss
templates/CWP/CWP/PageTypes/Layout/SitemapPage.ss
templates/Layout/Page.ss
templates/Layout/Page_results.ss
templates/Layout/Security.ss
templates/SilverStripe/Blog/Includes/BlogSideBar.ss
templates/SilverStripe/Blog/Model/Layout/Blog.ss
templates/SilverStripe/Blog/Model/Layout/BlogPost.ss
templates/SilverStripe/Blog/Model/Layout/Blog_profile.ss
templates/SilverStripe/IFrame/Layout/IFramePage.ss
templates/SilverStripe/Registry/Layout/RegistryPage.ss

As per design update - there was already a grid system in place, however
it was for Bootstrap 3, and the Bootstrap 4 grid has changed. Most notably
a new break size was added at the smaller end of the scale, pushing all
others "up one", so `md` became `lg`. This commit adds more consistency
throughout all templates, and conforms to newer design tweaks for Watea
(which uses Starter as a base via SS4 theme cascades).
Closes #95

FIX shift to 8 + 3 grid system

---

templates/SilverStripe/Blog/Model/Layout/Blog.ss

FIX Blog breadcrumbs offset is only shown when SideBarView is not enabled

---

templates/SilverStripe/Blog/Includes/BlogSideBar.ss
templates/SilverStripe/Blog/Model/Layout/Blog.ss
templates/SilverStripe/Blog/Model/Layout/BlogPost.ss
templates/SilverStripe/Blog/Model/Layout/Blog_profile.ss

Fixes https://github.com/silverstripe/cwp-starter-theme/issues/108
* Blog
* Blog post
* Blog profile
Also, blog profile author name title now looks smaller when compared to the main page title:
Instead of:
These templates now support content blocks for content, instead of assuming it will be in `$Content`.

FIX Blog template now offsets correctly when a sidebar exists but has no content

---

templates/BreadcrumbsTemplate.ss

Fixes https://github.com/silverstripe/cwp-watea-theme/issues/50

FIX Make breadcrumbs aria labels more generic so it can be used in search context as well

---

templates/SilverStripe/Registry/Layout/RegistryPage.ss

Resolves https://github.com/silverstripe/silverstripe-registry/issues/52
Will need to be merge up as well

FIX Sanitise data class in 'view imported data history' link so it resolves correctly

---

templates/Includes/CommentPagination.ss
templates/Includes/Pagination.ss

Bootstrap tells it to inherit its text colour and remove the text underline if the anchor doesn't have a href attribute.
Fixes https://github.com/silverstripe/cwp-starter-theme/issues/121

FIX Pagination text colour is now accessible on hovering the current page button

---

templates/SilverStripe/IFrame/Layout/IFramePage.ss

Fixes https://github.com/silverstripe/silverstripe-iframe/issues/43
Requires https://github.com/silverstripe/silverstripe-iframe/pull/44

FIX Add CMS configurable title for iframe to tell screenreaders it contains frame content

---

templates/Includes/MainNav.ss

**High priority:** The currently selected page navigation links do not have their visible text as part of their accessible name.
**Impact:** Speech input users can interact with a webpage by speaking the visible text labels of menus, links, and buttons that appear on the screen. It is confusing to speech input users when they say a visible text label they see, but the speech command does not work because the component's accessible (programmatic) name does not match the visible label. It is a best practice to have the accessible name to include and begin with the visible text.
**Solution:** Remove the aria-label so that the visible text serves as the accessible name. In order to indicate to non-sighted users which link is the current page, add an aria-current attribute instead to the menu …

FIX Add aria-current attribute to selected page nav links

---

templates/Includes/FormFieldMessage.ss

**High priority:**
The error messages for incorrect date entry is visually provided but focus is not directed to the notifications to alert non-sighted users.
**Impact:** Non-sighted users will not know if their submission was successful or why their entry failed to submit if focus is not sent directly to the error message. They will be forced to manually search for the error message, which may be frustrating and time-consuming.
**Solution:** 
Use an aria alert region on the div container. The error container must be present in the DOM on page load for the error message to be spoken by most screen readers. aria- atomic=true is necessary to make Voiceover on iOS read the error messages after more than one invalid submission.
For more information on this technique, please refer to: …

FIX Provide focus on error messages

---

templates/Includes/AvailableMonths.ss

**Low priority:** The #nav-link.badge.badge-primary links' accessible names derived from the aria-label attributes do not start with the visible label text.
**Impact:** Speech input users can interact with a webpage by speaking the visible text labels of menus, links, and buttons that appear on the screen. It is confusing to speech input users when they say a visible text label they see, but the speech command does not work because the component's accessible (programmatic) name does not match the visible label. It is a best practice to have the accessible name to include and begin with the visible text.
**Solution:** Ensure that the accessible name matches and/or starts with the visible label text. Remove the redundant title attributes to avoid duplication of the accessible name.
Also …

FIX Ensure that the accessible name starts with the visible label text

---

templates/CommentsInterface.ss

Based on accessibility feedback:
> On submission of the "Post" button, focus should be sent to the submission message in order to confirm the user action.
>
>The easiest way to achieve this is to give the <p> element a tabindex of -1 and call its focus() method.
We opted not to include the focus() call, as the tabindex (likely along with the anchor in the URL) was sufficient for VoiceOver to announce the message first.
(This replicates a [template change in the comments module](https://github.com/silverstripe/silverstripe-comments/pull/289))

NEW Add tabindex="-1" to comment submission message for a11y support

---

templates/Includes/LanguageSelector.ss

**High priority:**
In narrow viewports, the language selector button has no accessible name.
**Impact:** Without a discernible, accessible textual name, there is no way to describe to screen reader users the purpose of a button. When there is no name, there is no clear description of the destination, purpose, function or action for the non-text content when it is intended to be used as a control.
**Solution:** Add an aria-label to the button.

FIX Add aria-label to Language selector for narrow viewports

---

templates/Includes/Footer.ss
templates/Includes/MainNav.ss
templates/Page.ss

Based on accessibility feedback:
> - The main landmark should be at top level but there is a main landmark contained within another main landmark. It is best practice to have one main landmark.
> - Aside / complimentary content is ancillary content to the main theme of a document or page and should therefore be at top level, but it is nested within another landmark.
> - "Navigation" has been included in the aria-labels for the main and footer `<nav>` landmarks which causes unnecessary duplication within their accessible name
> - It is a best practice to use both HTML5 and ARIA landmarks to ensure all content is contained within a navigational region. In HTML5, you should use elements like `<header>`, `<nav>`, `<main>`, and `<footer>`. Their ARIA counterparts are `role="banner"`, …

NEW Improve ARIA Landmarks by adjusting role attributes

---

templates/Includes/PageUtilities.ss

**Medium priority:** The "Print", "Subscribe", "Facebook", "Twitter" and external link icon fonts are included as a unicode value in the accessible name.
**Impact:** If the icon is not hidden from assistive technology users, the meaningless unicode value will be announced, which may confuse users.
**Solution:** Add an aria-label to the links to provide the accessible name and remove the redundant <span> and title elements.
**NOTE:** This PR excludes the external link icon font, we will still need to address this issue.

FIX Add aria-labels and remove redundant span attributes

---

templates/SilverStripe/Blog/Model/Layout/Blog.ss

The `<main>` element should signify the main content, not a child of that element.
Fixes #117.

FIX Drop "main" role from Blog template to improve accessibility

---

templates/Includes/FilteredUpdates.ss

Found a redundant title while making my way through other issues which causes an unnecessary duplication of the accessible name of the link.

FIX Remove redundant FilteredUpdates title attribute

---

templates/Layout/Page_results.ss

**Medium priority:** When a user submits a site search, focus is sent back up to the top of the page rather than to the results notification message.
**Impact:** The results of a search is clear to sighted users but for non- sighted users, who would have to manually search for the results. Sending focus to the results notification helps to orientate and confirm user actions.
**Solution:** On activation or submission of the search button, focus should be sent to the results element that confirms the user action.

FIX Add tabindex to focus the results notification message

---

templates/Includes/UpdateTags.ss

**Low priority:** The title attributes for the "CWP 2.0 Highlights and Upgrade Tips", "CWP 2.0 and Upgrading", "Introducing CWP 2.0", "CWP 2.0", "Releases", "SilverStripe" and "Upgrading" links double up on the accessible name of the links.

FIX Remove redundant tags title

---

templates/Includes/EventItem.ss
templates/Includes/NewsItem.ss

Reads out the News/Events holder title first which usually just "News/Events". I don't think this information is providing anymore benefit to the user.

FIX Remove redundant titles from News and Events

---

templates/Includes/SitemapNode.ss
templates/Includes/SitemapNodeChildren.ss

The list of links is wrapped in a ul with a role of tablist, and each of the list items has role="tab", but it is not a tabbed interface, so this is quite incorrect. All this incorrect ARIA should be removed. The content is is a simple list of links, and no ARIA is required.
Remove all the redundant title attributes on the links. "Go to Home page" doesn't add anything useful to a link called "Home". It only gets in the way visually, especially for screen magnification users, and aurally for screen reader or text-to-speech users.

FIX Remove redundant roles and titles from sitemap

---

templates/Includes/LanguageSelector.ss

Related: https://github.com/silverstripe/cwp-starter-theme/pull/137
Even at wider viewports, when the component has an accessible name, that accessible name does not clearly reflect the component's function--it only names a language. A better name visual label and accessible name would be "Language", with, in this case, English and Māori being the options to choose from. Otherwise, on an English page, what is a button called "English" supposed to do?

FIX Add accessible name to reflect the components function
